ALTER TABLE `nilai_raport`
  DROP `mtk1`,
  DROP `mtk2`,
  DROP `mtk3`,
  DROP `mtk4`,
  DROP `mtk5`,
  DROP `ipa1`,
  DROP `ipa2`,
  DROP `ipa3`,
  DROP `ipa4`,
  DROP `ipa5`,
  DROP `ips1`,
  DROP `ips2`,
  DROP `ips3`,
  DROP `ips4`,
  DROP `ips5`,
  DROP `b_ing1`,
  DROP `b_ing2`,
  DROP `b_ing3`,
  DROP `b_ing4`,
  DROP `b_ing5`,
  DROP `b_ind_jml`,
  DROP `mtk_jml`,
  DROP `ipa_jml`,
  DROP `ips_jml`,
  DROP `b_ing_jml`;

  ALTER TABLE `nilai_raport` CHANGE `b_ind1` `sem1` INT(11) NULL DEFAULT NULL, CHANGE `b_ind2` `sem2` INT(11) NULL DEFAULT NULL, CHANGE `b_ind3` `sem3` INT(11) NULL DEFAULT NULL, CHANGE `b_ind4` `sem4` INT(11) NULL DEFAULT NULL, CHANGE `b_ind5` `sem5` INT(11) NULL DEFAULT NULL;